### PR TITLE
Add support for the ppc64le architecture

### LINKED ISSUE #5: Support for ppc64le
Missing support for `ppc64le` (Power8 and later) processors. Architectures `ppc64` and `x86_64` are currently supported.

Are there any plans on adding support for this architecture in the future?

### PR DESCRIPTION
**Pull request by jjhursey**
* Resolves #5

### CODE REVIEW

**Comment by jjhursey** [comment]
I'm curious if the project maintainers had a chance to review this PR.

**Comment by mplegendre** [comment]
The changes look technically fine (from an eyeballing). Is this patch related to Robert Blackmore@IBM's spindle efforts?

**Comment by jjhursey** [comment]
Yeah. I'm working with him on this. These are all of the changes we think we need for `ppc64le` support. Limited testing is looking good so far.

**Comment by mplegendre** [comment]
I just merged this, then spotted it was pointed at master rather than the devel branch and had to revert it. Can you resubmit this, but pointed at the devel branch?

We're trying to keep master pinned at the last release.  Thanks.

**Comment by jjhursey** [comment]
Sorry I was swamped with travel/deadlines, and this got lost in the shuffle. I'll retarget the PR to the devel branch today.

**Pull request merged**
